### ISSUE TITLE
adding link of this plugin on official plugin repo 

### ISSUE THREAD

**Issue by prateekrastogi** [ragingwind/next-manifest#1]
Hi,

Thanks a lot for this awesome plugin. I especially found the Manifest component quite cool. When I was trying to make my web app PWA, I found that this plugin combined with [next-offline](https://github.com/hanford/next-offline) made a perfect combo. However, as this plugin was not listed in official next repo, I wasted few hours looking for appropriate way to create manifest file.  Given that manifest file is pretty much mandatory for proper PWA, wouldn't it be better if you can create a pull request to add a link for this plugin on [nextjs plugins official repo](https://github.com/zeit/next-plugins) to help others looking for solving the same problem?

**Comment by ragingwind** [comment]
Thanks for using it. It will be listed on the plugin list after updating a few things with [next-workbox](https://github.com/ragingwind/next-workbox)
