### ISSUE TITLE
No more icon generating ?

### ISSUE THREAD

**Issue by ScreamZ** [ragingwind/next-manifest#15]
Hello :)

No more icons generation for people not using `now` ?

Why ? :) https://github.com/ragingwind/pwa-manifest-icons seems to handle this

Regards

**Comment by ragingwind** [comment]
First of all, sorry for your inconvenience. I need to keep this app simple as much as mvp for working on now or not. so generating icon was pulled out from this. as you mentioned, you can use another solutions for icons generating

**Comment by airtonix** [comment]
what's the point of this package then?
