### ISSUE TITLE
Generate /manifest inside .next/static?

### ISSUE THREAD

**Issue by joaovieira** [ragingwind/next-manifest#2]
This is currently generating the `/manifest` folder inside `$CWD/static`. In my case, for example, the next app lives inside `/app`, so this is not compatible. Also, rather than "polluting" the user's `/static`, would it be possible to build into the `.next/static` generated folder? Don't know the details of how to do that, though, so it's food for thought.

Apart from that, this is looking good. Good job 👍 

(Edit: same for `next-workbox`)

**Comment by ragingwind** [comment]
/static is the general way to get resources from next.js. .next will be exist for built application code not resources I think. so /static is the best way to manage it. for example, manifest.json would not be generated in every built time.

**Comment by joaovieira** [comment]
@ragingwind you may have skipped the first half of the issue, but the problem is that it assumes the next app structure is at the root which is not always the case. It should use `config.dir` to get the source of the app.

I'd argue that `.next` is the general place for generated assets/resources from webpack - such as this one. `/assets` is a user-defined folder. Both `.next` and `/static` are static resources, but one is generated and the other is not. As an example, `next-offline` generates the manifest into `.next`. 

Regardless of where it is outputted, though, the original issue is still there. Next apps are not mandatorily at the workspace root.

If you want to re-open I'll be happy. Else I'll look into `next-offline`.

**Comment by tomevans18** [comment]
This is partly related, so I didn't want to create another ticket.

When you use Zeit Now to deploy the application, even though it states in the logs the manifest is being built it doesn't appear in the static files and then obviously causes a 404. I think this is because only locally pushed files can exists in the app directory and this is why other plugins use .next for files created at build time. This obviously needs more investigation to confirm, so I will do some digging, but I feel this is a legit bug.

**Comment by tomevans18** [comment]
Update on the above. Pushing output into .next does not fix the issue. This means its not running on a now "build" for some reason. Will investigte some more...

**Comment by tomevans18** [comment]
As this is a different to the original question/bug I am going to raise a new issue.

**Comment by jsardev** [comment]
I agree on this. Generated statics suit better in `.next`. `/static` suits better for manually added content.

**Comment by ragingwind** [comment]
I don't think so. I always bet plugin's results must be far away from core behavior. manifest, sw.js is still considered that as a resource like imagemin plugin. I can transform, update and generate it but not in core, `.next`. After 3.0.1 you can set output path but I still don't recommend that.
