### ISSUE TITLE
breaks next-offline

### ISSUE THREAD

**Issue by Enalmada** [ragingwind/next-manifest#5]
next-manifest looks nice!  I am using [next-offline](https://github.com/hanford/next-offline) for service worker and wanted something additional to give me pwa manifest.  When I add this to my current project, the service worker stops working.  It would be awesome to either make them compatible or document why they can't be used together.

**Comment by orditeck** [comment]
Same issue here.

**Comment by orditeck** [comment]
@ragingwind if you've got any lead I can follow, I could try to fix this.

**Comment by hanford** [comment]
@Enalmada @orditeck Hmm, this more likely an issue with next-offline. Feel free to open an issue there and we can investigate!

**Comment by shawninder** [comment]
I made a repo dedicated to getting to the bottom of this, and although that repo reproduces the problem, the problem disappears when I reproduce it in test form. Anyone want to take a look and see if they can figure out what I'm doing wrong?

https://github.com/shawninder/next-manifest-sw-clash
