### ISSUE TITLE
broken as of Next.js 8.0.2

### ISSUE THREAD

**Issue by Yzrsah** [ragingwind/next-manifest#9]
Next.js 8.0.1 - works

Next.js 8.0.2 - exporting withManifest() produces:
```
Entry module not found: Error: Can't resolve './src' in '/Users/foo/site'
_document.js chunk not found
```

**Comment by MontoyaAndres** [comment]
Did you could resolve it?

**Comment by Yzrsah** [comment]
@MontoyaAndres Yes it is fixed by removing the async export:
https://github.com/Yzrsah/next-manifest

@ragingwind Are you living, can you update this please?

**Comment by alecrae** [comment]
@Yzrsah nice work, it solved the issue for me so I'm using your fork in the meantime.

**Comment by ragingwind** [comment]
It might be help https://github.com/ragingwind/next-manifest/commit/303ac1b427282d4d7f59b20bcda7b15a3dde6aaf
